### ISSUE TITLE
Underlying connection closed: Unexpected error during a send operation...

### ISSUE THREAD

**Issue by machis21** [AfterShip/aftership-sdk-net#14]
Hello,

since few days every call from the ConnectionAPI causes the error "Underlying connection closed: Unexpected error during a send operation..."

For example:

ConnectionAPI connection = new ConnectionAPI(APIKEY);
List<Tracking> listTrackings = connection.getTrackings(1);

The Code:

ConnectionAPI connection = new ConnectionAPI(APIKEY);
Tracking newTracking = new Tracking(trackingNumber);
connection.createTracking(1);
Does add the Tracking to AfterShip but throws the same error-

This applies to every code in the code example.

I also cloned the repository and tried to run the Unit Tests they do throw the same errors

Do you have any idea how to help me to fix it?

Thank you so much

**Comment by Bossa573** [comment]
@machis21 is there any error stacks?
it's very hard to debug with the an error message only.
also, did you try to call AfterShip API directly with REST client such as postman, under the same network and with the same API key?

**Comment by machis21** [comment]
Thanks for the quick reply, the error in detail is "Authentication failed. The remote party has closed the transport flow". 
I tried making the same call with AfterShip API directly with REST client postman, under the same network and with the same API key and it works fine.

**Comment by machis21** [comment]
Thanks for the support, I was able to solve. It was a problem with the TLS certificate. Regards
