### ISSUE TITLE
Additional response fields.

### ISSUE THREAD

**Issue by IvanGrodno** [AfterShip/aftership-sdk-net#8]
Thank you for SDK.
Is it not planned to extend the answer model of the method of obtaining track numbers / numbers? Unfortunately at the moment I can not get values with the help of SDK fields: shipment_weigth, shipment_weight_unit, signed_by (this field is in the response model, but it is always null). If you make a request directly to Api - all this data is there.

**Comment by Bossa573** [comment]
There would be a plan for modernizing the .net SDK and will also handle this issue, 
this ticket will be closed at the moment
