### ISSUE TITLE
tracking_destination_country is required

### ISSUE THREAD

**Issue by sametgungoren** [AfterShip/aftership-sdk-net#9]
Hi Team!

We are using destinationCountryISO3 parameter to add Destination Country but the library still want tracking destination country. Unable to fill tracking destination country with .Net Library

`{
    "data": {
        "tracking": {
            "customer_name": "Armin Grünbaum",
            "destination_country_iso3": "DEU",
            "emails": [
                "AGruenbaum@gmx.de"
            ],
            "order_id": "4394",
            "order_id_path": "",
            "slug": "postnl-3s",
            "title": "4394",
            "tracking_account_number": "",
            "tracking_number": "3SMYPA3322507",
            "tracking_postal_code": "91629",
            "tracking_ship_date": "today"
        }
    },
    "meta": {
        "code": 4009,
        "message": "`tracking_destination_country` is required.",
        "type": "BadRequest"
    }
}`

Thanks.

**Comment by Bossa573** [comment]
Please provide tracking_destination_country for the couriers which requiring such keys
